### PR TITLE
Fix exception handling in AsyncDefaultAdmissionRequestMutator

### LINKED ISSUE #283: AsyncDefaultAdmissionRequestMutator doesn't handle NotAllowedException correctly
`AsyncDefaultAdmissionRequestMutator` catches `NotAllowedException` directly, but they are nested in a `CompletionException`. This is correctly done in the `AsyncDefaultAdmissionRequestValidator`. As a result you get a 500 response on the HTTP endpoint, instead of a 200 with a `AdmissionResponse` with a 403 status and the message as root cause.

It's also an inconvenience that the `AsyncAdmissionController` accepts a `Valiator`, but not a `Mutator` and you have to provide the `CompletableFuture.supplyAsync()` boilerplate code by yourself.

### PR DESCRIPTION
**Pull request by Donnerbart**
Fixes #283

* Fixes exception handling in `AsyncDefaultAdmissionRequestMutator`
* Adds convenient `AsyncAdmissionController(Mutator<T> mutator)` constructor
* Shows simplified usage of `Mutator` and `Validator` classes in `io.javaoperatorsdk.webhook.sample.commons.AdmissionControllers`
* Cleanup of code base (I'm already sorry for this one :sweat_smile:)

# Code Coverage

## `main`
image

## `bugfix/fix-async-mutator-exception-handling`
image

### CODE REVIEW

File: core/src/main/java/io/javaoperatorsdk/webhook/admission/mutation/AsyncDefaultAdmissionRequestMutator.java [hunk 1]
```diff
@@ -15,37 +15,48 @@
...
-          .supplyAsync(() -> AdmissionUtils.notAllowedExceptionToAdmissionResponse(e));
-    }
-    return admissionResponse;
+    final var operation = Operation.valueOf(admissionRequest.getOperation());
+    final var originalResource = (T) getTargetResource(admissionRequest, operation);
+    final var clonedResource = cloner.clone(originalResource);
+    return asyncMutator.mutate(clonedResource, operation)
+        .thenApply(resource -> admissionResponseFromMutation(originalResource, resource))
+        .exceptionally(e -> {
+          if (e instanceof CompletionException) {
```
Comment (Donnerbart) [inline core/src/main/java/io/javaoperatorsdk/webhook/admission/mutation/AsyncDefaultAdmissionRequestMutator.java:53]: This is the actual fix

File: core/src/main/java/io/javaoperatorsdk/webhook/admission/mutation/AsyncDefaultAdmissionRequestMutator.java [hunk 2]
```diff
@@ -15,37 +15,48 @@
...
   private final Cloner<T> cloner;
 
-  public AsyncDefaultAdmissionRequestMutator(AsyncMutator<T> mutator) {
+  public AsyncDefaultAdmissionRequestMutator(Mutator<T> mutator) {
     this(mutator, new ObjectMapperCloner<>());
   }
 
-  public AsyncDefaultAdmissionRequestMutator(AsyncMutator<T> mutator, Cloner<T> cloner) {
-    this.mutator = mutator;
+  public AsyncDefaultAdmissionRequestMutator(Mutator<T> mutator, Cloner<T> cloner) {
```
Comment (Donnerbart) [inline core/src/main/java/io/javaoperatorsdk/webhook/admission/mutation/AsyncDefaultAdmissionRequestMutator.java:30]: This is the internal convenience constructor to enable the use of a `Mutator` for an async endpoint.

File: samples/commons/src/main/java/io/javaoperatorsdk/webhook/sample/commons/AdmissionControllers.java [hunk 3]
```diff
@@ -19,46 +19,22 @@ public class AdmissionControllers {
...
   public static AsyncAdmissionController<Ingress> asyncMutatingController() {
-    return new AsyncAdmissionController<>(
-        (AsyncMutator<Ingress>) (resource, operation) -> CompletableFuture.supplyAsync(() -> {
-          if (resource.getMetadata().getLabels() == null) {
-            resource.getMetadata().setLabels(new HashMap<>());
-          }
-          resource.getMetadata().getLabels().putIfAbsent(MUTATION_TARGET_LABEL, "mutation-test");
-          return resource;
-        }));
+    return new AsyncAdmissionController<>(new IngressMutator());
```
Comment (Donnerbart) [inline samples/commons/src/main/java/io/javaoperatorsdk/webhook/sample/commons/AdmissionControllers.java:31]: This demonstrates the usage of the new convenience constructor. In general this shows how you can de-deduplicate the code for mutators and validators by using old-school inner classes that can be used for sync and async endpoints.

**Comment by Donnerbart** [comment]
**sigh** Obviously it wasn't enough to import the code style into IDEA. Sadly `./mvnw formatter:format -Dconfigfile=$PWD/contributing/eclipse-google-style.xml --file pom.xml` doesn't do anything on my machine, although `./mvnw formatter:validate -Dconfigfile=$PWD/contributing/eclipse-google-style.xml --file pom.xml` reports the same failure like the CI. Any hint how I can fix the formatting?

File: samples/commons/src/main/java/io/javaoperatorsdk/webhook/sample/commons/AdmissionControllers.java (hunk 3 above)
Comment (csviri) [reply samples/commons/src/main/java/io/javaoperatorsdk/webhook/sample/commons/AdmissionControllers.java:31]: If you simply run `mvn clean install`, that should fix it (if remember correctly)

Comment (Donnerbart) [reply samples/commons/src/main/java/io/javaoperatorsdk/webhook/sample/commons/AdmissionControllers.java:31]: Sadly not, `mvn clean install` is successful and no files are changed. The Quarkus/JOSDK repos with spotless worked indeed fine for me.

**Review by csviri — APPROVED** [review]
LGTM, thank you!

File: samples/commons/src/main/java/io/javaoperatorsdk/webhook/sample/commons/AdmissionControllers.java (hunk 3 above)
Comment (csviri) [reply samples/commons/src/main/java/io/javaoperatorsdk/webhook/sample/commons/AdmissionControllers.java:31]: Ahh, sry, for me neither. Would you like to do the migration to spotless or should I do it (not sure in what timeline) ?

Comment (Donnerbart) [reply samples/commons/src/main/java/io/javaoperatorsdk/webhook/sample/commons/AdmissionControllers.java:31]: I'm not a Maven guy (anymore), but I can surely have a look. I'd say this should go in to a new PR and then I rebase this one later?

Comment (csviri) [reply samples/commons/src/main/java/io/javaoperatorsdk/webhook/sample/commons/AdmissionControllers.java:31]: yes, that would be ideal, thx!

Comment (Donnerbart) [reply samples/commons/src/main/java/io/javaoperatorsdk/webhook/sample/commons/AdmissionControllers.java:31]: I've re-created the branch from `main`, cherry-picked each commit and ran `spotless:apply` for all of them. So all commits should be compliant with the code formatting now.

**Comment by csviri** [comment]
@Donnerbart the build fails, could you pls take a look. Thx

**Comment by Donnerbart** [comment]
It was just a missing import, an oversight when I re-created the branch.

**Review by csviri — APPROVED** [review]
LGTM, thx @Donnerbart
